runtime: python27
api_version: 1
threadsafe: true
skip_files:
 - ^node_modules$
 - ^src$
 - ^static$
 - ^tests$
 - ^.git$
handlers:
- url: /images/(.*)$
  static_files: dist/images/\1
  upload: dist/images/.*
- url: /robots.txt
  static_files: dist/robots.txt
  upload: dist/robots.txt
- url: /main.js
  static_files: dist/main.js
  upload: dist/main.js
- url: /sw.js
  static_files: dist/sw.js
  upload: dist/sw.js
- url: /manifest.json
  static_files: dist/manifest.json
  upload: dist/manifest.json
- url: /version.json
  static_files: dist/version.json
  upload: dist/version.json
- url: /favicon.ico
  static_files: dist/favicon.ico
  upload: dist/favicon.ico
- url: /(.*)$
  static_files: dist/index.html
  upload: dist/index.html
